trigger:
  - main
pr:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  apphostProj: 'src/eShop.AppHost/eShop.AppHost.csproj'
  nugetCacheDir: '$(Pipeline.Workspace)/.nuget/packages'
  # Azure Artifacts feed URL
  feedUrl: 'https://pkgs.dev.azure.com/konnecttransit/_packaging/konnecttransit/nuget/v3/index.json'
  # Package version (bump automatically per build)
  packageVersion: '1.0.$(Build.BuildId)'

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET 9 SDK'
    inputs:
      version: '9.0.x'
      includePreviewVersions: false

  - bash: |
      echo "##vso[task.setvariable variable=DOTNET_CLI_TELEMETRY_OPTOUT]1"
      echo "##vso[task.setvariable variable=DOTNET_SKIP_FIRST_TIME_EXPERIENCE]1"
    displayName: 'Set CI env vars'

  # Authenticate the agent to Azure Artifacts (for restore + push)
  - task: NuGetAuthenticate@1
    displayName: 'Authenticate to Azure Artifacts'

  # NuGet package cache (must be a real path)
  - task: Cache@2
    displayName: 'Cache NuGet'
    inputs:
      key: 'nuget | $(Agent.OS) | **/*.csproj, **/*.props, **/*.targets, **/nuget.config'
      restoreKeys: 'nuget | $(Agent.OS)'
      path: '$(nugetCacheDir)'

  - bash: |
      mkdir -p "$(nugetCacheDir)"
    displayName: 'Ensure cache dir'

  # Restore (write to the cache dir)
  - bash: |
      dotnet restore "$(apphostProj)"
    displayName: 'Restore'
    env:
      NUGET_PACKAGES: '$(nugetCacheDir)'

  # Build
  - bash: |
      dotnet build "$(apphostProj)" -c "$(buildConfiguration)" --no-restore
    displayName: 'Build'
    env:
      NUGET_PACKAGES: '$(nugetCacheDir)'

  # Test – discover *Tests.csproj and run; skip if none
  - bash: |
      set -e
      echo "Searching for test projects..."
      mapfile -t projects < <(find . -type f -name "*Tests.csproj" -o -name "*.Tests.csproj")
      if [ ${#projects[@]} -eq 0 ]; then
        echo "No test projects found. Skipping dotnet test."
        exit 0
      fi
      echo "Found ${#projects[@]} test project(s):"
      printf ' - %s\n' "${projects[@]}"
      for proj in "${projects[@]}"; do
        echo "Running tests in: $proj"
        dotnet test "$proj" -c "$(buildConfiguration)" --no-build --verbosity normal
      done
    displayName: 'Test'
    env:
      NUGET_PACKAGES: '$(nugetCacheDir)'

  # -------------------------------
  # NEW: Pack + Push to Artifacts
  # -------------------------------

  # Pick a packable library project (example: WebAppComponents)
  # If a project isn't packable by default, add /p:IsPackable=true
  - bash: |
      mkdir -p "$(Build.ArtifactStagingDirectory)/packages"
      dotnet pack src/WebAppComponents/WebAppComponents.csproj \
        -c "$(buildConfiguration)" \
        -o "$(Build.ArtifactStagingDirectory)/packages" \
        /p:ContinuousIntegrationBuild=true \
        /p:Version="$(packageVersion)"
      echo "Packages created:" && ls -la "$(Build.ArtifactStagingDirectory)/packages"
    displayName: 'Pack NuGet package(s)'
    env:
      NUGET_PACKAGES: '$(nugetCacheDir)'

  - bash: |
      dotnet nuget push "$(Build.ArtifactStagingDirectory)/packages/*.nupkg" \
        --source "$(feedUrl)" \
        --api-key azdo
    displayName: 'Push packages to Azure Artifacts'

  # (Optional) Publish the packages folder as a pipeline artifact too
  - publish: $(Build.ArtifactStagingDirectory)/packages
    artifact: packages
    displayName: 'Publish packages as pipeline artifact'

  # Publish AppHost output as artifact (your existing output)
  - bash: |
      dotnet publish "$(apphostProj)" \
        -c "$(buildConfiguration)" \
        -o "$(Build.ArtifactStagingDirectory)/apphost"
    displayName: 'Publish AppHost'
    env:
      NUGET_PACKAGES: '$(nugetCacheDir)'

  - publish: $(Build.ArtifactStagingDirectory)
    artifact: drop
    displayName: 'Publish artifacts'
